blog/urls.py
from django.urls import path
from .views import all_blogs,detail

app_name = 'blog'

urlpatterns = [
    path('', all_blogs, name='all_blogs'),
    path('<int:blog_id>', detail, name='detail')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='portfolio')
]

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=150)
    date = models.DateField()
    discription = models.TextField()

portfolio/models.py
from django.db import models

class Portfolio(models.Model):
    title = models.CharField(max_length=150)
    discription = models.CharField(max_length=250)
    image = models.ImageField(upload_to = 'portfolio/images')
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request,'blog/all_blogs.html',{'blogs':blogs})

def detail(request,blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Portfolio
# Create your views here.

def home(request):
    projects = Portfolio.objects.all()

    return render(request, 'portfolio/home.html', {'projects' : projects})

blog/templates/blog/all_blogs.html
{% load static %}
<link rel="stylesheet" href="{% static 'blog/css/blogpage.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
<body>
    
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar" style="background-color: #e3f2fd;">
    <div id="logo">
       <a href="{% url 'portfolio' %}"> <img  width="50%"  src="{% static 'portfolio/images/logo.png' %}" alt=""></a>
    </div>
    <div class="navbar">
        <a class="navbar-brand" href="{% url 'portfolio' %}">HOME</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav  clearfix">
            <a class="nav-item nav-link" href="{% url 'portfolio' %}">Portfolio <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="https://gitlab.com/s_uktamov/">Gitlab</a>
            <a class="nav-item nav-link" href="https://s3-us-west-2.amazonaws.com/udacity-printer/production/certificates/6d44ade2-05bc-4616-b592-afe3bff09ac7.pdf">Certificate</a>
            
            <a  href="{% url 'blog:all_blogs' %}" class="btn btn-success float-right">BLOG</a>
            </div>
        </div>
    </div>
</nav>
<h2 class="display-4">Bu mening Bloglarim {{blogs.count}} ta</h2>
<div class="container-fluid">
    <div class="blog-wrap">
        {% for blog in blogs %}
        <div class='col-3'>
            <a href="{% url 'blog:detail' blog.id %}"> <h2 id="title" style="padding: 5px; color: darkgreen;">{{blog.title}}</h2>   </a>
             <h5 class="lead">     {{blog.date |date:'d  b Y'}} </h5>
             <p class="lorem">{{blog.discription|safe | truncatechars:100}}</p>
        </div>
        {% endfor %}
    </div>

</div>
</body>

blog/templates/blog/detail.html
<h1 style="text-align: center;">{{blog.title}}</h1>
<h5 style="text-align: center;">{{blog.date}}</h5>
<p>{{blog.discription|safe}}</p>

portfolio/templates/portfolio/home.html
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/homepage.css' %}">
<link rel="stylesheet" href="{% static 'portfolio/css/bootstrap.min.css' %}">

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar" style="background-color: #e3f2fd;">
        <div id="logo">
           <a href=""> <img  width="50%"  src="{% static 'portfolio/images/logo.png' %}" alt=""></a>
        </div>
        <div class="navbar">
            <a class="navbar-brand" href="#">HOME</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav  clearfix">
                <a class="nav-item nav-link" href="#portfolio">Portfolio <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="https://gitlab.com/s_uktamov/">Gitlab</a>
                <a class="nav-item nav-link" href="https://s3-us-west-2.amazonaws.com/udacity-printer/production/certificates/6d44ade2-05bc-4616-b592-afe3bff09ac7.pdf">Certificate</a>
                <a  href="{% url 'blog:all_blogs' %}" class="btn btn-success float-right">BLOG</a>
                </div>
            </div>
        </div>
    </nav>
    
    
    <div class="rasm">
        <h1 class="display-4" style="margin: 15px;">Bu mening qilgan ishlarim</h1>
        <img width="60%" src="{% static 'portfolio/images/Brain.png' %}" alt="bu rasm">
    
    </div>
    
    <div class="section_01" id="portfolio" >
        {% for project in projects %}
            <div class="section_02">
                <h1 class="display-4">{{project.title}}</h1>
                <p >{{project.discription}}</p>
                <img style="width: 200px;" src="{{project.image.url}}" alt=""><br>
    
                {% if project.url %}
                <a href="{{project.url}}">link</a>
                {% endif %}
            </div>   
        {% endfor %}
    </div>
    
</body>